name: Benchmark Performance Testing

on:
  push:
    branches: [ 'main' ]

jobs:
  benchmark:
    name: Check performance regeression for Node App.
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Setup Node
        uses: actions/setup-node@v1
      
      - name: Run benchmark
        run: cd node && npm install && node bench.js | tee output.txt
      
      - name: Store benchmark result
        uses: rhysd/github-action-benchmark@v1
        with:
          name: Benchmark.js Benchmark
          tool: 'benchmarkjs'
          output-file-path: output.txt
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: true
          alert-threshold: '130%'
          comment-on-alert: true
          fail-on-alert: true
          #alert-comment-cc-users: '@thomaspoignant'